# -*- coding: utf-8 -*-
"""Human posture Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-opfqahsP9lWN8ZDzDx78m5iQGYcYuaB

“This project uses MediaPipe Pose AI to detect human body landmarks from an image and then classifies posture as Standing, Sitting, or Hands Up. It can be used in surveillance, fitness tracking, and human activity monitoring systems.”

“Here I download the MediaPipe Pose Landmarker model, which is already trained to detect human body joints like shoulders, hips, knees, and wrists.”
"""

!wget -O pose_landmarker.task https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/latest/pose_landmarker_full.task

!ls

# ============================================
# HUMAN POSTURE DETECTION + POSTURE NAME
# MediaPipe TASKS API (STABLE)
# ============================================

!pip install -U mediapipe opencv-python

import cv2
import mediapipe as mp
import matplotlib.pyplot as plt
from google.colab import files
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# --------------------------------------------
# Upload image
# --------------------------------------------
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

image = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
h, w, _ = image.shape

# --------------------------------------------
# Load Pose Landmarker model
# --------------------------------------------
base_options = python.BaseOptions(
    model_asset_path="pose_landmarker.task"
)

options = vision.PoseLandmarkerOptions(
    base_options=base_options,
    running_mode=vision.RunningMode.IMAGE
)

detector = vision.PoseLandmarker.create_from_options(options)

# --------------------------------------------
# Run detection
# --------------------------------------------
mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image_rgb)
result = detector.detect(mp_image)

# --------------------------------------------
# Posture classification function
# --------------------------------------------
def classify_posture(lm):
    left_shoulder = lm[11]
    right_shoulder = lm[12]
    left_hip = lm[23]
    right_hip = lm[24]
    left_knee = lm[25]
    right_knee = lm[26]
    left_wrist = lm[15]
    right_wrist = lm[16]

    shoulder_y = (left_shoulder.y + right_shoulder.y) / 2
    hip_y = (left_hip.y + right_hip.y) / 2
    knee_y = (left_knee.y + right_knee.y) / 2
    wrist_y = (left_wrist.y + right_wrist.y) / 2

    if wrist_y < shoulder_y:
        return "Hands Up"
    elif abs(hip_y - knee_y) < 0.08:
        return "Sitting"
    else:
        return "Standing"

# --------------------------------------------
# Draw landmarks, bounding box & posture name
# --------------------------------------------
if result.pose_landmarks:
    lm = result.pose_landmarks[0]

    posture_name = classify_posture(lm)

    x_vals, y_vals = [], []

    for p in lm:
        x = int(p.x * w)
        y = int(p.y * h)
        x_vals.append(x)
        y_vals.append(y)

        cv2.circle(image_rgb, (x, y), 3, (255, 0, 0), -1)

    # Bounding box
    x_min, x_max = min(x_vals), max(x_vals)
    y_min, y_max = min(y_vals), max(y_vals)

    cv2.rectangle(
        image_rgb,
        (x_min, y_min),
        (x_max, y_max),
        (0, 255, 0),
        2
    )

    # Posture label
    cv2.putText(
        image_rgb,
        f"Posture: {posture_name}",
        (x_min, y_min - 10),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.9,
        (0, 255, 0),
        2
    )

else:
    print("❌ No human posture detected")

# --------------------------------------------
# Show output
# --------------------------------------------
plt.figure(figsize=(8, 8))
plt.imshow(image_rgb)
plt.axis("off")
plt.title("Human Posture Detection with Posture Name")
plt.show()